project:
  type: website
  output-dir: docs

website:
  title: "Francis Felici"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/franfram
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: cosmo
    css: styles.css



